filebeat.inputs:
  - type: filestream
    id: novack-backend-logs
    enabled: true
    paths:
      - /var/log/app_logs/*.log
      - /var/log/*.log
    fields:
      app: 'novack-backend'
      environment: 'development'
      source: 'filestream'
    fields_under_root: true
    json.keys_under_root: true
    json.overwrite_keys: true
    json.message_key: 'message'
    scan_frequency: 5s
    harvester_limit: 5
    close_inactive: 5m
    close_renamed: true
    close_removed: true
    clean_inactive: 24h

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata:
      host: 'unix:///var/run/docker.sock'

# Configuración de output
output.logstash:
  hosts: ['logstash:5044']
  bulk_max_size: 2048
  worker: 2
  timeout: 60s
  backoff.init: 1s
  backoff.max: 30s
  ssl.enabled: false

# Configuración de logging
logging.level: debug
logging.to_stderr: true
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  keepfiles: 7
  permissions: 0644

# Configuración de monitoreo (simplificada)
monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ['elasticsearch:9200']

# Configuración adicional para estabilidad
queue.mem:
  events: 8192
  flush.min_events: 1024
  flush.timeout: 2s

# Configuración de gestión de archivos
filebeat.registry:
  path: /usr/share/filebeat/data/registry
  file_permissions: 0644
  flush: 1s
